name: Release

on:
  workflow_dispatch:
    inputs:
      zig_version:
        description: Zig version to use
        required: true
        type: string
      release_version:
        description: Release version
        required: true
        type: string

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Zig
      uses: goto-bus-stop/setup-zig@v2.2.0
      with:
        version: ${{ inputs.zig_version }}

    - name: Build
      run: zig build --release=small

    - name: Generate Files List
      id: files
      run: |
        $files = Get-ChildItem -Path zig-out/bin -Filter *.exe -Recurse | ForEach-Object { $_.FullName }
        $newline_files = $files -join "`n"
        Add-Content -Path $env:GITHUB_OUTPUT -Value "files=$newline_files"

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.files.outputs.files }}
        tag_name: ${{ inputs.release_version }}
